name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24.19.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Install
        run: pnpm install

      - name: Lint Scripts
        run: pnpm lint:eslint

      - name: Lint Format
        run: pnpm lint:fmt

      - name: Lint Types
        run: pnpm lint:ts

      - name: Unit Test
        run: pnpm coverage

      - name: Build
        run: pnpm build
