name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '25.5.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install

      - name: Lint Scripts
        run: pnpm lint:eslint

      - name: Lint Format
        run: pnpm lint:fmt

      - name: Lint Types
        run: pnpm lint:ts

      - name: Unit Test
        run: pnpm test

      - name: Build
        run: pnpm build
