name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn install

      - name: Lint Scripts
        run: yarn lint:eslint

      - name: Lint Format
        run: yarn lint:fmt

      - name: Lint Types
        run: yarn lint:ts

      - name: Unit Test
        run: yarn test

      - name: Build
        run: yarn build
